### ISSUE TITLE
No easy way to use sagas with multiple aggregates

### ISSUE THREAD

**Issue by kthe** [eventflow/EventFlow#302] opened 2017-03-10 21:17 UTC
Maybe I am missing something but.. it seems like the sagas needs a little work in the usability area.
When working with more then one aggregate, I can not find a good way to locate the saga given the domain event..

Some sample code.

```
using System;
using System.CodeDom;
using System.Threading;
using System.Threading.Tasks;
using EventFlow.Aggregates;
using EventFlow.Sagas;
using Produce.Inbound.Logistics.Models.Shipment.Events;
using Produce.Internal.Logistics.Models.ArrivedShipment.Events;

namespace Saga.PackageRegistrationFromShipment
{
    public class PackageRegistrationFromShipmentSagaLocator : ISagaLocator
    {
        public Task<ISagaId> LocateSagaAsync(
            IDomainEvent domainEvent, 
            CancellationToken cancellationToken)
        {
            // note: (maybe) should only be used if no other 
            // matching methods where found. i.e default behavour..

            // issue: events from different 
            // aggregates have different sources for saga id

            // for ShipmentAggregate.ShipmentArrivedEvent
            // var sagaId = $"saga-{domainEvent.GetIdentity()}
            // for ArrivedShipmentAggregate.PackageRegisteredEvent
            // var sagaId = $"saga-{((PackageRegisteredEvent)domainEvent).OriginalShipmentId}

            // problem: how to distinct events except from using the IDomainEvent.AggregateEvent
           // in a switch type of way?

           // note: can only be used if all events comes from the same aggregate..
            var aggregateId = domainEvent.GetIdentity();
            var id = new PackageRegistrationFromShipmentSagaId($"saga-{aggregateId.Value}");

            return Task.FromResult<ISagaId>(id);
        }

        // note: what would be good if called
        public Task<ISagaId> LocateSagaAsync(
            ShipmentArrivedEvent domainEvent,
            CancellationToken cancellationToken)
        {
            // note: event from 'shipment' aggregate (owner?)

            // note: the event does not contain 
            // the aggregate id except as metadata..

            // want to use
            // var aggreagteId = domainEvent.GetIdentity();

            // but have to use (if method was called), the business shipment id as part of the saga id
            var aggregateId = domainEvent.BusinessId.Value;

            var id = new PackageRegistrationFromShipmentSagaId($"saga-{aggregateId}");

            return Task.FromResult<ISagaId>(id);
        }

        // note: what would be good if called
        public Task<ISagaId> LocateSagaAsync(
            PackageRegisteredEvent domainEvent,
            CancellationToken cancellationToken)
        {
            // note: event from 'arrived shipment' (aka package) aggregate

            // use the original shipment id as the saga id
            var aggregateId = domainEvent.OriginalShipmentId;

            // use the 
            var id = new PackageRegistrationFromShipmentSagaId($"saga-{aggregateId}");

            return Task.FromResult<ISagaId>(id);
        }
    }
}

```

**Comment by rasmus** [comment] 2017-03-10 22:19
@kthe You are definitely right, sagas is relatively new to EventFlow and I haven't done any iterations on the concept yet.

Regarding how to get the saga ID, here I haven't been able to come up generic method for generating saga IDs. The problem is that I depends very much on how you structure your domain and events. There are a few different solutions you could choose from

- Pick one aggregate ID from among the aggregate the saga interacts with. However this locks you to a single saga, so not good
- Generate a deterministic ID using `Identity<>.NewDeterministic` used on data present in all events in the sagas lifetime. Slightly better, but would still be cumbersome
- As a saga represents a process, it might be worthwhile to give it an ID that you explicitly reference in your events and domain. The initiating domain event would then simply create a new random ID which is then referenced in each part of the process
- Query the mapping somewhere else, e.g. from a read model.

If you have a good idea for a general concept, then let me know.

**Comment by rasmus** [comment] 2017-04-05 12:39
@kthe Did you find a solution?

**Comment by houseme-kyle** [comment] 2017-04-10 15:34
@rasmus we using EventFlow throughout our system and have recently ran into this problem. What we have done is use a NoSQL store for the purpose of generating the mapping between contexts and maintaining it. 

The reason this work is because sometime during the lifetime of each instance in a flow, the relationship is know, so it is only a matter of recording this relationship for when it is needed upon initializing.

**Comment by kthe** [comment] 2017-04-10 15:57
@rasmus. And we settled for using metadata similar to the docs.


måndag 10 april 2017 skrev houseme-kyle <notifications@github.com>:

**Comment by rasmus** [comment] 2017-04-10 18:35
@houseme-kyle and @kthe, great, if you have any specific suggestions on how the saga API might be improved, then let me know.

**Comment by rasmus** [comment] 2017-04-10 19:03
@kthe and @houseme-kyle if you have implemented your own event persistence, I can recommend that you take a look at `TestSuiteForEventStore` for test inspiration. Especially make sure that the support for optimistic concurrency is tested.

**Comment by ppXD** [comment] 2017-04-11 00:12
~

**Comment by ppXD** [comment] 2017-04-11 00:16
- [ ]

**Comment by rasmus** [comment] 2017-04-15 16:46
I'll close this issue, let me know if you disagree.

**Closed by rasmus** 2017-04-15 16:46 UTC
Labels: question
