### ISSUE TITLE
ObjectDisposed Errors ASP.Net core 2.0 

### ISSUE THREAD

**Issue by wgtmpeters** [eventflow/EventFlow#429] opened 2018-02-23 16:50 UTC
I followed the examples which describe how to start ASP.Net 2.0 core application with the Autofac Container.
We are doing this:
           // Add framework services.
            services.AddMvc();

            var containerBuilder = new ContainerBuilder();
            EventFlowOptions.New
                .UseAutofacContainerBuilder(containerBuilder)
                .AddDefaults(typeof(EventFlowAssemblyDefaults).Assembly);

            containerBuilder.Populate(services);
            this.ApplicationContainer = containerBuilder.Build();
            return new AutofacServiceProvider(ApplicationContainer);

Which works fine for the first call to the WebHost, but the second one will throw disposed errors when resolving an interfaces for  the createInstance of the Saga in the factory.

We have one event for example that is handled by a normal service which works fine everytime ,but creating or loading a saga fails eveytime when we controller is called for a second time.
Line 110 of the aggregateFactory parameters[parameterInfo.Position] = resolver.Resolve(parameterInfo.ParameterType); 
resolver.Disposed = true, so somehow the Resolver is disposed at this point.

We still get to the normal subscriber of the event, but it is impossible for us to Load or Update a Saga the second time around. 

Could this be a bug in how the Resolver LifeTime is managed or are we doing something wrong here?

**Comment by wgtmpeters** [comment] 2018-02-24 16:39
I think it has something todo with the memoryCache that is used.

            var storeAggregateSagaAsync = await GetUpdateAsync(
                sagaDetails.SagaType,
                cancellationToken)
                .ConfigureAwait(false);

This GetUpdateAsync uses a memoryCache for the call to the Saga and it seems that everytime this cached function is used the Resolver is disposed.

Will try and debug a bit more,  can I disable the caching somehow?

**Comment by rasmus** [comment] 2018-02-24 18:09
@wgtmpeters If you want to disable memory caching on reflection objects, simply register your own implementation of `IMemoryCache` that doesn't do anything.

**Comment by rasmus** [comment] 2018-02-24 18:10
There is a difference in EventFlow when using the .NET 4.5.1 assembly and using .NET standard. It might be the cause.

https://github.com/eventflow/EventFlow/blob/develop/Source/EventFlow/EventFlowOptions.cs#L224

**Comment by wgtmpeters** [comment] 2018-02-24 20:21
I will try to register one with no caching, will this have noticeable impact on performance?

**Comment by wgtmpeters** [comment] 2018-02-25 00:39
It does work when I remove the In MemoryCache.
Have also tried with the MemoryCache version which you have for dotnet 4.5.1 (migrated to Microsoft.Extensions.Caching.Memory) but that has the same issue.

return Task.FromResult<Func<ISagaId, ISourceId, Func<ISaga, CancellationToken, Task>, CancellationToken, Task<IReadOnlyCollection<IDomainEvent>>>>(
                        (id, sid, u, c) => (Task<IReadOnlyCollection<IDomainEvent>>)genericMethodInfo.Invoke(this, new object[] { id, sid, u, c }));

When debugging at the genericMethodInfo.Invoke part the resolver is disposed.

For now we can work with a stub memory cache but how much does not having one impact performance?

**Comment by rasmus** [comment] 2018-02-25 19:19
@wgtmpeters I don't know about the performance hit as I haven't done any tests. Caching of reflection results in EventFlow wasn't done because I observed any performance problems, but because its recommended. My gut feeling is that you shouldn't be worried, but I don't know.

If you do have some relative numbers from a production system, let me know. I don't own the services that use EventFlow at work anymore.

**Comment by rasmus** [comment] 2018-02-25 20:06
@wgtmpeters I created a test that can reproduce it in #429

**Comment by rasmus** [comment] 2018-02-25 20:13
@wgtmpeters Found the bug, will release a fix asap

**Comment by rasmus** [comment] 2018-02-25 22:01
Fixed in 0.54.3261

**Closed by rasmus** 2018-02-25 22:01 UTC
Labels: bug

**Comment by wgtmpeters** [comment] 2018-02-25 22:14
Thank you for the quick followup
